Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -24,24 +24,28 @@ jobs:
             perl \
             fakeroot \
             dpkg-dev \
-            xz-utils \
-            ldid
+            xz-utils
 
       - name: Install Theos
         run: |
-          git clone --recursive https://github.com/theos/theos.git $HOME/theos
+          git clone --recursive https://github.com/theos/theos.git "$HOME/theos"
 
-      - name: Download iOS SDK
+      - name: Install iOS SDK
         run: |
-          git clone https://github.com/theos/sdks.git /tmp/sdks
-          mkdir -p $HOME/theos/sdks
-          cp -R /tmp/sdks/iPhoneOS16.5.sdk $HOME/theos/sdks/
+          git clone --depth 1 https://github.com/theos/sdks.git /tmp/sdks
+          mkdir -p "$HOME/theos/sdks"
 
-      - name: Build rootless package
-        env:
-          THEOS: ${{ github.workspace }}/../theos
+          if [ -d "/tmp/sdks/iPhoneOS16.5.sdk" ]; then
+            cp -R "/tmp/sdks/iPhoneOS16.5.sdk" "$HOME/theos/sdks/"
+          else
+            echo "iPhoneOS16.5.sdk not found"
+            ls -la /tmp/sdks
+            exit 1
+          fi
+
+      - name: Build
         run: |
-          export THEOS=$HOME/theos
+          export THEOS="$HOME/theos"
           make clean
           make package FINALPACKAGE=1
 
